<?php

$books = array(
	'mt' => array(
		'xml' =>'61-Mt.xml',
		'title' => 'Mateo',
		'chapters' => 24,
		'dir' => 'matthew',
	),
	'mk' => array(
		'xml' =>'62-Mk.xml',
		'title' => 'Marcos',
		'chapters' => 16,
		'dir' => 'mark',
	),
	'lk' => array(
		'xml' =>'63-Lk.xml',
		'title' => 'Lucas',
		'chapters' => 24,
		'dir' => 'luke',
	),
	'jn' => array(
		'xml' =>'64-Jn.xml',
		'title' => 'Juan',
		'chapters' => 21,
		'dir' => 'john',
	),
	'ac' => array(
		'xml' =>'65-Ac.xml',
		'title' => 'Hechos',
		'chapters' => 28,
		'dir' => 'acts',
	),
	'ro' => array(
		'xml' =>'66-Ro.xml',
		'title' => 'Romanos',
		'chapters' => 16,
		'dir' => 'romans',
	),
	'1co' => array(
		'xml' =>'67-1Co.xml',
		'title' => '1 Corintios',
		'chapters' => 16,
		'dir' => '1_corinthians',
	),
	'2co' => array(
		'xml' =>'68-2Co.xml',
		'title' => '2 Corintios',
		'chapters' => 13,
		'dir' => '2_corinthians',
	),
	'ga' => array(
		'xml' =>'69-Ga.xml',
		'title' => 'Gálatas',
		'chapters' => 6,
		'dir' => 'galatians',
	),
	'eph' => array(
		'xml' =>'70-Eph.xml',
		'title' => 'Efesios',
		'chapters' => 6,
		'dir' => 'ephesians',
	),
	'php' => array(
		'xml' =>'71-Php.xml',
		'title' => 'Filipenses',
		'chapters' => 4,
		'dir' => 'philippians',
	),
	'col' => array(
		'xml' =>'72-Col.xml',
		'title' => 'Colosenses',
		'chapters' => 4,
		'dir' => 'colossians',
	),
	'1th' => array(
		'xml' =>'73-1Th.xml',
		'title' => '1 Tesalonicenses',
		'chapters' => 5,
		'dir' => '1_thessalonians',
	),
	'2th' => array(
		'xml' =>'74-2Th.xml',
		'title' => '2 Tesalonicenses',
		'chapters' => 3,
		'dir' => '2_thessalonians',
	),
	'1ti' => array(
		'xml' =>'75-1Ti.xml',
		'title' => '1 Timoteo',
		'chapters' => 6,
		'dir' => '1_timothy',
	),
	'2ti' => array(
		'xml' =>'76-2Ti.xml',
		'title' => '1 Timoteo',
		'chapters' => 4,
		'dir' => '2_timothy',
	),
	'tit' => array(
		'xml' =>'77-Tit.xml',
		'title' => 'Tito',
		'chapters' => 3,
		'dir' => 'titus',
	),
	'phm' => array(
		'xml' =>'78-Phm.xml',
		'title' => 'Filemón',
		'chapters' => 1,
		'dir' => 'philemon',
	),
	'heb' => array(
		'xml' =>'79-Heb.xml',
		'title' => 'Hebreos',
		'chapters' => 13,
		'dir' => 'hebrews',
	),
	'jas' => array(
		'xml' =>'80-Jas.xml',
		'title' => 'Santiago',
		'chapters' => 5,
		'dir' => 'james',
	),
	'1pe' => array(
		'xml' =>'81-1Pe.xml',
		'title' => '1 Pedro',
		'chapters' => 5,
		'dir' => '1_peter',
	),
	'2pe' => array(
		'xml' =>'82-2Pe.xml',
		'title' => '2 Pedro',
		'chapters' => 3,
		'dir' => '2_peter',
	),
	'1jn' => array(
		'xml' =>'83-1Jn.xml',
		'title' => '1 Juan',
		'chapters' => 5,
		'dir' => '1_john',
	),
	'2jn' => array(
		'xml' =>'84-2Jn.xml',
		'title' => '2 Juan',
		'chapters' => 1,
		'dir' => '2_john',
	),
	'3jn' => array(
		'xml' =>'85-3Jn.xml',
		'title' => '3 Juan',
		'chapters' => 1,
		'dir' => '3_john',
	),
	'jud' => array(
		'xml' =>'86-Jud.xml',
		'title' => 'Judas',
		'chapters' => 1,
		'dir' => 'jude',
	),
	're' => array(
		'xml' =>'87-Re.xml',
		'title' => 'Apocalipsis',
		'chapters' => 22,
		'dir' => 'revelation',
	),
);
